name: Build FarmPam Frontend

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Setup
        uses: actions/checkout@v3

      - name: NodeJS Setup
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0
          cache: npm

      - name: Package Install
        run: npm ci

      - name: Proejct Build
        run: npm run build

      # GitHub Actions CLI 환경에서 S3 사용자 권한의 aws 접속
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      # vue 빌드한 /build를 s3로 업로드
      - name: Upload /build to S3
        run: aws s3 cp --recursive --region us-west-1 dist s3://farmpam-dara-e

      - name: Cloudfront invalidate
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID }} --paths '/*'